theme.ale <- theme(
  # plot.title=element_text(size=20,vjust=2,face="bold"),
  text=element_text(family="Helvetica"),
  axis.line=element_line(color="black"),
  axis.text= element_text(colour="black", size=15, angle=0,face = "plain"),
  panel.background=element_rect(fill="white",colour="black"),
  panel.grid=element_line(colour="grey"),
  plot.margin=unit(c(1,2,0,0),"cm"),
  axis.text.x  = element_text(size=13,hjust=.5, vjust=.5),
  axis.title.x=element_text(size=18,vjust=0.3),
  axis.text.y  = element_text(size=13,hjust=1, vjust=0),
  axis.title.y=element_text(size=18,vjust=0.8),
  strip.text.x  = element_text(size = 13, colour ="black", angle = 0),
  plot.title= element_text(size=15),
  legend.background =element_rect("white"),
  #legend.position=c(0.6,0.15),
  legend.direction="vertical",
  legend.margin=unit(0.5,units="cm"),
  legend.key=element_rect("white",colour="white"),
  legend.text =element_text(size=14),
  legend.title = element_text(colour="black", size=18),
  legend.key.width=unit(2,"line"),
  panel.grid.major = element_line(colour = "grey90", size = 0.2),
  panel.grid.minor = element_line(colour = "grey98", size = 0.5),
  panel.margin=unit(0.5,units="cm"),
  strip.background = element_rect(fill = "grey80", colour = "grey50", size = 0.2))+
  facet_wrap(~region,scales="free_x")
